{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.observationsRole.name }}
  labels:
    app: {{ .Values.rbac.observationsRole.name }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["{{ .Values.rbac.observationsRole.resourceName }}"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
{{- end }}