{{- if not .Values.awsSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.k8sSecretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.selectorLabels.app }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
{{- end }}
