apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.aws.region }}
    objects: |
      - objectName: "POSTGRES_USER"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: "db_username"
      - objectName: "POSTGRES_PASSWORD"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: "db_password"
      - objectName: "POSTGRES_DB"
        objectType: "secretsmanager"
        jmesPath:
          - path: dbname
            objectAlias: "db_name"
  secretObjects:
    - secretName: {{ .Values.secrets.k8sSecretName }}
      type: Opaque
      data:
        - objectName: "db_username"
          key: "POSTGRES_USER"
        - objectName: "db_password"
          key: "POSTGRES_PASSWORD"
        - objectName: "db_name"
          key: "POSTGRES_DB"
