apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.aws.region }}
    objects: |
      - objectName: "POSTGRES_PASSWORD"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: {{ .Values.secrets.k8sSecretName }}
      type: Opaque
      data:
        - objectName: "POSTGRES_PASSWORD"
          key: "POSTGRES_PASSWORD"
