apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-eks.backendName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "ai-eks.backendName" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "ai-eks.backendName" . }}
  template:
    metadata:
      labels:
        app: {{ include "ai-eks.backendName" . }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "ai-eks.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "ai-eks.backendName" . }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          envFrom:
            {{- if .Values.backend.configMapName }}
            - configMapRef:
                name: {{ .Values.backend.configMapName }}
            {{- end }}
            {{- if .Values.backend.secretName }}
            - secretRef:
                name: {{ .Values.backend.secretName }}
            {{- end }}
          {{- if .Values.backend.awsSecrets.enabled }}
          volumeMounts:
            - name: backend-secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
          {{- end }}
          {{- with .Values.backend.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.backend.awsSecrets.enabled }}
      volumes:
        - name: backend-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.backend.awsSecrets.secretProviderClassName }}
      {{- end }}
