{{- if and .Values.backend.secrets .Values.backend.secretName .Values.backend.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "ai-eks.backendName" . }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
